import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import Session from "./utils/session";
import { SessionProvider } from "next-auth/react";
import Client from "./components/Client";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ElectroniCart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
          <Client/>
          {children}
          <Footer />
      </body>
    </html>
  );
}
