import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import Client from "./components/Client";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ElectroniCart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Client />
        {children}
        <Footer />
      </body>
    </html>
  );
}
